### PR TITLE
Create seed data and write filter population/handling logic

### PR DESCRIPTION
**Pull request by leecmoses**
@garrettdavid1 This is the work that was completed the other day. Thanks again for taking the time to teach me! 🙏🏼

### CODE REVIEW

**Comment by leecmoses** [comment]
@garrettdavid1 @wuhugh Should we change the settings for the repo so that a review and an approval is required before a pull request can be merged?

**Comment by wuhugh** [comment]
Good idea, I added branch protection onto `master`.

**Review by wuhugh — COMMENTED** [review]
Let's add some comments. I think it'll make it for other contributors and so David doesn't have to explain it every time.

**Review by garrettdavid1 — APPROVED** [review]
Commented filters.js and app.js.

**Pull request merged**
